import {
  contentSchema,
  type BrandPlan,
  type BusinessPlan,
  type ContentPack,
  type ProductSpec,
} from "../schemas";
import { runStructuredAgent } from "./base";

export async function runContentAgent(
  plan: BusinessPlan,
  brand: BrandPlan,
  product: ProductSpec
) {
  return runStructuredAgent({
    system:
      "You are SITEFLIP ContentAgent. Generate starter landing copy JSON: hero, value proposition, features, how it works, pricing, CTA, FAQ, footer. Safe generated content only.",
    user: { plan, brand, product },
    schema: contentSchema,
    heuristic: () => heuristicContent(plan, brand, product),
  });
}

function heuristicContent(
  plan: BusinessPlan,
  brand: BrandPlan,
  product: ProductSpec
): ContentPack {
  return {
    hero: {
      headline: brand.tagline,
      subheadline: plan.valueProposition || brand.brandDescription,
      cta: "Start free",
    },
    features: (product.mvpFeatures.length ? product.mvpFeatures : plan.mvpScope)
      .slice(0, 4)
      .map((f) => ({
        title: f,
        body: `Included in the ${plan.businessName} MVP scope.`,
      })),
    howItWorks: [
      { step: "Describe", detail: "Share your workflow and goals." },
      { step: "Configure", detail: "Set up the core path in minutes." },
      { step: "Launch", detail: "Invite your team and iterate." },
    ],
    benefits: [
      `Built for ${plan.targetCustomer}`,
      "Simple pricing",
      "Ship faster than building from scratch",
    ],
    pricingCopy: plan.pricing.tiers
      .map((t) => `${t.name}: €${t.priceMonthlyEur}/mo — ${t.features.join(", ")}`)
      .join(" · "),
    faq: [
      {
        q: "Is this a finished production SaaS?",
        a: "Factory V1 generates a blueprint and starter landing preview. Full product code requires further approved builds.",
      },
      {
        q: "Are payments live?",
        a: "Payment architecture is prepared. Activation requires your approval and provider keys.",
      },
    ],
    about: brand.brandDescription,
    contact: "Contact form placeholder — wire to your email provider.",
    footer: `© ${new Date().getFullYear()} ${brand.brandName}. Starter landing generated by SITEFLIP Factory V1.`,
    termsPlaceholder:
      "Terms of Service placeholder — requires legal review before publishing.",
    privacyPlaceholder:
      "Privacy Policy placeholder — requires legal review before publishing.",
    seoMetadata: {
      title: `${brand.brandName} — ${brand.tagline}`,
      description: brand.brandDescription.slice(0, 155),
    },
    labeledAssumptions: [
      "[AI_HYPOTHESIS] Copy is AI-generated from specs — not user-approved until you approve",
      "[VERIFIED] Legal placeholders are not publishable legal documents",
    ],
  };
}
