import {
  codeArtifactSchema,
  type BrandPlan,
  type BusinessPlan,
  type CodeArtifact,
  type ContentPack,
  type SeoPack,
} from "../schemas";
import { scanGeneratedContent } from "../sandbox";
import { runStructuredAgent } from "./base";

/**
 * DeveloperAgent (MVP): generates starter landing page artifacts in sandbox only.
 * Does NOT overwrite SITEFLIP core. Does NOT claim full production SaaS.
 */
export async function runDeveloperAgent(input: {
  plan: BusinessPlan;
  brand: BrandPlan;
  content: ContentPack;
  seo: SeoPack;
}) {
  const result = await runStructuredAgent({
    system:
      "You are SITEFLIP DeveloperAgent. Generate landing page React/TSX file contents as JSON {files:[{path,language,content,purpose}],...}. Sandbox only. completeness must be landing_page_only. sandboxOnly true.",
    user: input,
    schema: codeArtifactSchema,
    heuristic: () => heuristicCode(input),
  });

  // Safety scan
  for (const file of result.data.files) {
    const scan = scanGeneratedContent(file.content);
    if (!scan.safe) {
      file.content = `/* BLOCKED: ${scan.findings.join("; ")} */\nexport default function Blocked(){return null}`;
    }
  }

  // Force honest completeness for MVP
  result.data.completeness = "landing_page_only";
  result.data.sandboxOnly = true;
  result.data.labeledAssumptions = [
    ...(result.data.labeledAssumptions ?? []),
    "MVP DeveloperAgent generates starter landing artifacts only",
    "Not a complete production SaaS",
    "Files are sandbox outputs — not written into SITEFLIP core",
  ];

  return result;
}

function heuristicCode(input: {
  plan: BusinessPlan;
  brand: BrandPlan;
  content: ContentPack;
  seo: SeoPack;
}): CodeArtifact {
  const { brand, content, plan } = input;
  const landing = `"use client";

/**
 * SANDBOX ARTIFACT — generated by SITEFLIP DeveloperAgent
 * Completeness: landing_page_only
 * Not linked into SITEFLIP core routes.
 */
export default function LandingPage() {
  return (
    <main style={{ background: "${brand.colorDirection.background}", color: "#f4f4f5", minHeight: "100vh", fontFamily: "system-ui" }}>
      <section style={{ maxWidth: 960, margin: "0 auto", padding: "80px 24px", textAlign: "center" }}>
        <p style={{ color: "${brand.colorDirection.primary}", letterSpacing: "0.2em", fontSize: 12, textTransform: "uppercase" }}>${brand.brandName}</p>
        <h1 style={{ fontSize: "clamp(2rem,5vw,3.5rem)", marginTop: 16 }}>${escapeJs(content.hero.headline)}</h1>
        <p style={{ color: "#a1a1aa", marginTop: 16, fontSize: 18 }}>${escapeJs(content.hero.subheadline)}</p>
        <button style={{ marginTop: 32, background: "${brand.colorDirection.primary}", color: "white", border: 0, padding: "12px 24px", borderRadius: 12, fontWeight: 600 }}>
          ${escapeJs(content.hero.cta)}
        </button>
      </section>
      <section style={{ maxWidth: 960, margin: "0 auto", padding: "40px 24px", display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))" }}>
        ${content.features
          .map(
            (f) => `<div style={{ border: "1px solid rgba(255,255,255,0.1)", borderRadius: 16, padding: 20 }}>
          <h3>${escapeJs(f.title)}</h3>
          <p style={{ color: "#a1a1aa", fontSize: 14 }}>${escapeJs(f.body)}</p>
        </div>`
          )
          .join("\n")}
      </section>
      <section style={{ maxWidth: 720, margin: "0 auto", padding: "40px 24px" }}>
        <h2>Pricing</h2>
        <p style={{ color: "#a1a1aa" }}>${escapeJs(content.pricingCopy)}</p>
        <ul>
          ${plan.pricing.tiers
            .map(
              (t) =>
                `<li style={{ marginTop: 8 }}><strong>${escapeJs(t.name)}</strong> — €${t.priceMonthlyEur}/mo</li>`
            )
            .join("")}
        </ul>
      </section>
      <section style={{ maxWidth: 720, margin: "0 auto", padding: "40px 24px 80px" }}>
        <h2>FAQ</h2>
        ${content.faq
          .map(
            (item) => `<details style={{ marginTop: 12, border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, padding: 12 }}>
          <summary>${escapeJs(item.q)}</summary>
          <p style={{ color: "#a1a1aa", fontSize: 14 }}>${escapeJs(item.a)}</p>
        </details>`
          )
          .join("")}
      </section>
      <footer style={{ textAlign: "center", color: "#52525b", padding: 24, fontSize: 12 }}>
        Generated by SITEFLIP AI Business Factory · Preview only · Payments not activated
      </footer>
    </main>
  );
}
`;

  return {
    files: [
      {
        path: "sandbox/app/page.tsx",
        language: "tsx",
        content: landing,
        purpose: "Starter landing page preview",
      },
      {
        path: "sandbox/README.md",
        language: "markdown",
        content: `# ${brand.brandName} (Sandbox)

Generated by SITEFLIP DeveloperAgent.

- Completeness: **landing_page_only**
- Isolated from SITEFLIP core database
- Payments not activated
- Production deploy requires approval
`,
        purpose: "Sandbox documentation",
      },
    ],
    dependencies: ["next", "react", "react-dom", "typescript", "tailwindcss"],
    notes: [
      "Artifacts stored as factory outputs — not written over SITEFLIP source",
      "Preview rendered via /build/[id]/preview",
    ],
    completeness: "landing_page_only",
    sandboxOnly: true,
    labeledAssumptions: [
      "Only landing page starter generated in MVP",
      "Further autonomous coding is future architecture",
    ],
  };
}

function escapeJs(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}
